version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    network_mode: "host"

volumes:
  dbdata:

networks:
  laravel-network:
    driver: bridge
